### ISSUE TITLE
Connecting with NodeJS

### ISSUE THREAD

**Issue by wrxsti85** [jamesremuscat/EDDN#1]
Hi,

I am having a bit of difficulty connecting to the data network with a node JS application. I was hoping you could point me in the right direction. I've based it mostly off of your py script, but converted it to node which zmq does have a library for. My basic connection code is as follows:

var zmq = require('zmq'),
    subscriber = zmq.socket('sub'),
    zlib = require('zlib'),
    host = 'tcp://eddn-relay.elite-markets.net:9500';
    
subscriber.subscribe('');
subscriber.connect(host);

subscriber.on('message', function(reply){
  console.dir('Received message: ', reply.toString()); 
  /* I understand I'm not unzipping with zlib here, but the message listener never fires */
});

process.on('SIGINT', function(){
  subscriber.close();
});

I get no errors, but also no output so I am rather confused.
Any help would be much appreciated. Thanks!

**Comment by psema4** [comment]
Not certain (I can't test it at the moment) but it looks like the calls to subscribe() and connect() are in the wrong order.

If it helps, I also wrote a simple [node.js client](https://github.com/psema4/node-eddn-client) and posted it to the forums about a week ago. Haven't had a chance to get back there yet so apologies if you asked any questions there and did not receive a reply.

**Comment by wrxsti85** [comment]
Thanks for the reply psema4. To be honest I can't remember how long I waited before exiting, but I will certainly give that a try. Thanks for the suggestion, and I will update as soon as I've had a chance to give them a go!

**Comment by wrxsti85** [comment]
So I've had some time to test some of this out, but I'm not having much luck. I let my test build run for over an hour on Cloud9 IDE and received no response. I then began to think it had something to do with Cloud9 and the ports they allow traffic through. So I made an Amazon AWS Instance and made sure the security group had TCP:9500 open. Still no dice. I let the AWS Instance run for close to an hour and still received no responses. At this point I am getting really confused.

I wonder if I'm possible installing ZeroMQ wrong or missing dependencies. Would you be able to provide any incite into your installation process or server setup? Thanks!

**Comment by jamesremuscat** [comment]
What version of ZeroMQ are you running? Some versions are incompatible with others. I'm using libzmq.so.3.0.0 on the server.

**Comment by wrxsti85** [comment]
I'm currently using 3.2.2 on Ubuntu 14.04. I'll try dropping back to 3.0.0 later, and see if the results vary.

**Comment by psema4** [comment]
This one stumped me for a bit; I don't use console.debug in node very often.

If you change that call to a console.log you should have better luck. :)

**Comment by wrxsti85** [comment]
I actually tried console.log(), still no luck. I even copied the majority of the code directly from your node app and I'm still getting no response. I think James is on the right track. Something with my server config is likely wrong. Hopefully I'll have a chance to look at it shortly and find out.

**Comment by psema4** [comment]
Hrmm. It definitely works for me using 3.2.2 on Windows 7 (libzmq-v100-mt-3_2_2.dll specifically)

**Comment by wrxsti85** [comment]
I got it! So initially most of the Ubuntu setups I read for ZeroMQ advised to install "libzmq" and "libzmq-dev". After a bit more reading I installed "libzmq3" and "libzmq3-dev", and everything is working great. The responses start almost immediately and I am really looking forward to working on the client. Thanks so much guys, and I hope this helps someone else out in the future.
