### ISSUE TITLE
Example Python Code not Python 3 compatible - gevent 

### ISSUE THREAD

**Issue by j9ac9k** [jamesremuscat/EDDN#12]
I'm a bit of a git noob here, so please bear with me.  Was attempting to run the client.py file, I install pyzmq, and made the change to the print statement to accommodate python 3 syntax.

Problem comes with:
```
import zmq.green as zmq
...
ImportError: No module named 'gevent'
```

After spending a bunch of time trying to install gevent on a python 3 system, I eventually gave up, was wondering if gevent was needed for the example code.

**Comment by j9ac9k** [comment]
So after messing around w/ this a bunch, I settled with a work-around using conda environments, while not a fix, I thought I would post here in case anyone saw this:

I already had Miniconda3 installed on my windows based system (my preferred python distribution).

From the command prompt (not powershell):

```
>conda create -n EDDN python=2.7
>conda install pyzmq simplejson zlib gevent -n EDDN
>activate EDDN
>python client.py
```
when done with EDDN and wanting to go back to python 3
```
>deactivate
```

**Comment by AnthorNet** [comment]
gEvent is effectively not used in examples, thus it could be removed.
I'll try when I have 5 minutes.

**Comment by AnthorNet** [comment]
Try just changing:
    import zmq.green as zmq
to:
    import zmq

**Comment by j9ac9k** [comment]
This is the closest I got, but I'm still getting:

TypeError: the JSON object must be str, not 'bytes'

```
import zlib
import zmq
import json
import sys


def main():
    context = zmq.Context()
    subscriber = context.socket(zmq.SUB)

    subscriber.setsockopt_string(zmq.SUBSCRIBE, "")
    subscriber.connect('tcp://eddn-relay.elite-markets.net:9500')

    while True:
        market_json = zlib.decompress(subscriber.recv())
        market_data = json.loads(market_json)
        print(market_data)
        sys.stdout.flush()

if __name__ == '__main__':
    main()
```

I've tried 

```
import codecs

reader = codecs.getreader('utf-8')
...
    market_data = json.load(reader(market_json))
....
```
Then I get:

TypeError: the JSON object must be str, not 'StreamReader'

**Comment by AnthorNet** [comment]
Try that one: https://github.com/AnthorNet/EDDN/tree/EDDN-Monitor/examples/Python%203.4

**Comment by j9ac9k** [comment]
I confirmed both of those worked (after I opened the issue yesterday, I found those files posted in the forums); I didn't want to make a pull request suggesting that they be added as I didn't write them (what's the protocol for that sort of thing, I'm still new to development/open source/etc)?

Probably should have mentioned that earlier on...

**Comment by AnthorNet** [comment]
Closing, example is available in "master"
