### ISSUE TITLE
Proposal: Schema for shipyards

### ISSUE THREAD

**Issue by AnthorNet** [jamesremuscat/EDDN#16]
Reminder for new schema to discuss.

**Comment by AnthorNet** [comment]
See: https://github.com/jamesremuscat/EDDN/blob/master/schemas/shipyard-v1.0-draft.json

**Comment by Marginal** [comment]
Some comments:

I suggest removing the "minItems" restriction on ships , so that "ships": [] can indicate the absence of a shipyard.

Since only the name is mandatory all subscribers will need to handle it. This makes the fdId field redundant. Which field takes priority if the name and fdId conflict?
If you keep the fdId field I would suggest making it an "integer" for consistency with the commodity schema.

Do you intend to publish a list of names?
i.e. should that be "Cobra Mk III", "Cobra Mk. III" or "Cobra Mk.III" and "Type9", "Type-9" or "Type-9 Heavy" etc?

**Comment by AnthorNet** [comment]
Well since the fdID is only proposed by a few softwares and you don't know how long it will last, 
I tends not to rely on it too much. I think it should be to the subscribers to take care of that.
But it is thinking about future, as no one except those API software will use it for now ^^

fdID isn't an integer because on JSON, it can be unsigned and 0. By making it a number you can assure that it will not. See: http://spacetelescope.github.io/understanding-json-schema/reference/numeric.html

Agreed on removing the "minItems" on ships.

As for the list, we can add an enum field, but it would need us to be quick on updates when new ships are released.

I'll update in consequence.

**Comment by Marginal** [comment]
I'm not necessarily suggesting that "name" be an enum - as you point out this would break when a new ship is introduced. I suggest maintaining a master list of expected ship names, but outside of the schema.

**Comment by AnthorNet** [comment]
Or we can make the definition in the schema but let the field be a string

**Comment by Marginal** [comment]
Some further comments on your updated version:

You're missing "Dropship", "Imperial Courier" and "Imperial Clipper".
That should probably be "Sidewinder", not "SideWinder".

The last item (currently "Diamondback Explorer") in the enum should not be followed by a comma - it stops the schema passing [jsonschemalint](http://jsonschemalint.com/draft4/).

FYI [Here](https://gist.github.com/Marginal/958ae161f0953ea517ea) is a sample message in accordance with this schema.

**Comment by AnthorNet** [comment]
Yep it was a quick update based on your gist
I have them like ingame in my database.
perhaps will move them on wiki.

**Comment by Marginal** [comment]
I've updated [that gist](https://gist.github.com/Marginal/1d060332eb4ae15927a3) with the IDs of all of the currently flyable ships.

**Comment by Marginal** [comment]
Looks OK to me.
I still think fdId is redundant and that it's not clear what subscribers are supposed to do with it, so I won't generate it.

**Comment by AnthorNet** [comment]
@Marginal If it was for me, I woudn't have it either, some it's removed.
I think the proposal is good.

I leave for the week, but as soon as I return, I'll give it a shot in EDCE and ET-TD.

@maddavo What do you think of it ?
Does it suits your needs, your one of I think of when it comes to shipyard info ?

**Comment by Marginal** [comment]
This schema could be simplified with no loss of information - please see my push request #23.
[Here](https://gist.github.com/Marginal/699a8d318a6c8b019b84) is a sample message in the simplified schema that I'm suggesting in #23.

**Comment by Marginal** [comment]
Thanks. This draft schema is implemented in Marginal/EDMarketConnector@ae1678c.

**Comment by cmmcleod** [comment]
If anyone is looking for data, and schema examples everything is available here:

https://github.com/cmmcleod/coriolis/tree/master/data

Just an FYI :)
