### ISSUE TITLE
Make commodity schema strict wrt unknown elements

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/EDDN#2]
At present, the commodity schema allows unknown elements.

As EDDN matures, this should be made stricter, so that only defined elements are permitted.

**Comment by AnthorNet** [comment]
Done in next iteration fo v2 draft.
But ! JSON doesn't seems to handle insensitive enum, so have to lowercase all commodities.
May be check for another way to validate names.

**Comment by AnthorNet** [comment]
Closing has we have stated we will not do it
