### ISSUE TITLE
Sockets left open eventually exhausting available file handles

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/EDDN#29]
Every so often the gateway stops responding to HTTP requests. The logs show:

> Traceback (most recent call last):
>  File "/opt/eddn/env-2.7/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/baseserver.py", line 140, in _do_read
>  File "/opt/eddn/env-2.7/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/server.py", line 93, in do_read
>  File "/opt/eddn/env-2.7/lib/python2.7/site-packages/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/socket.py", line 309, in accept
>    client_socket, address = sock.accept()
> error: [Errno 24] Too many open files
>  WSGIServer at 0x7f07cd469190 fileno=12 address=0.0.0.0:8080 failed with error

It looks like the Bottle/gevent web server isn't closing connections, as there are hundreds left open at the moment.

This is the cause of the last several EDDN outages.

**Comment by AnthorNet** [comment]
Strange, does bottle need gevent in that case ?

**Comment by wolverine2710** [comment]
Don´t know enough of Bottle/gevent to be of real help. 
Googled and found out that that the latest version of gevent is relative new.
gevent-1.0.2.tar.gz (md5) 	Source 		2015-05-23 	1MB

Is that version currently used in EDDN?
