### ISSUE TITLE
StatsCollector has been broken after v0.4 release

### ISSUE THREAD

**Issue by jamesremuscat** [jamesremuscat/EDDN#30]
Something's happened to the StatsCollector, and it no longer does what it should. The reported values for 1min are always zero.

Steps to reproduce:
* Run a gateway
* Submit a message
* Visit /stats/ and see that tallies have been added for inbound (and either outbound or invalid)
* Wait a minute
* Hit refresh

Expected outcome: a string such as

`{"inbound": {"1min": 1, "60min": 1, "5min": 1}, "uptime": 62, "version": "0.5", "invalid": {"1min": 1, "60min": 1, "5min": 1}}`

Actual outcome:

`{"inbound": {"1min": 0, "60min": 1, "5min": 1}, "uptime": 62, "version": "0.5", "invalid": {"1min": 0, "60min": 1, "5min": 1}}`

Because of the heavy value people have placed on the stats pages, I'm blocking the 0.5 release on this issue.

This is a regression since v0.4.

**Comment by Marginal** [comment]
Cannot reproduce. With the current head I correctly see:
`{"inbound": {"1min": 2, "60min": 2, "5min": 2}, "uptime": 63, "version": "0.5", "outbound": {"1min": 2, "60min": 2, "5min": 2}}`

**Comment by Marginal** [comment]
Looking more carefully I see that you have been sending invalid messages. I can't reproduce the behavious that you're seeing with invalid messages either:
`{"inbound": {"1min": 1, "60min": 1, "5min": 1}, "uptime": 62, "version": "0.5", "invalid": {"1min": 1, "60min": 1, "5min": 1}}`

**Comment by AnthorNet** [comment]
Just tested on test gateway and can't reproduce it either.

**Comment by jamesremuscat** [comment]
Seems to be fairly reliably reproduceable on my home dev box plus my continuous-integration server, but not on my work dev box.

Just to check my sanity, could you run the test I committed above, and let me know that it passes?

**Comment by jamesremuscat** [comment]
Looks like there's something wonky going on with the call to `sleep(60)`, so in some circumstances updates are triggered more than once. I'm investigating.

**Comment by AnthorNet** [comment]
Can you told me how you run the tests ?
Didn't remember ^^

But be aware that Sleep is not always precise depending on OS and tick.

**Comment by jamesremuscat** [comment]
nosetests --with-xunit --with-xcoverage --cover-package=eddn --cover-erase --cover-inclusive

I've tried rewriting the method to compare to actual runtime, but the loop still gets triggered multiple times. This is baffling myself and my colleagues!

**Comment by AnthorNet** [comment]
Odd !
Might have come with the python update? No?

Anyway, well played^^

**Comment by Marginal** [comment]
So, fancy doing the postponed deployment tonight?
