### ISSUE TITLE
special modules

### ISSUE THREAD

**Issue by koreldan** [jamesremuscat/EDDN#35]
there are nothing that distinguish between special and normal modules.... like the shield generators and the prismatic shield generators

**Comment by AnthorNet** [comment]
See: https://github.com/Marginal/EDMarketConnector/issues/40

**Comment by Marginal** [comment]
Yes, the schema [says](https://github.com/jamesremuscat/EDDN/blob/master/schemas/outfitting-v1.0.json#L45) that such modules should be omitted.

See [comment](https://github.com/Marginal/EDMarketConnector/issues/40#issuecomment-155472176) under Marginal/EDMarketConnector#40 for rationale.

**Comment by koreldan** [comment]
Is planned any schema for "special modules"

**Comment by AnthorNet** [comment]
!if they are effectively dependant of the user sending the data, clearly not.

**Comment by koreldan** [comment]
Also the datas sent by "OCR Elite" are dependant from the correctness of datas sent by users ,  are those datas planned to be refused too ?

**Comment by AnthorNet** [comment]
Oh common, that is not comparable at all...
OCR Elite user all see the same commodities...

**Comment by koreldan** [comment]
yep, but numbers correctness are checked by users...

I meant simply that they could be managed as 4th batch of data ( like "commodities", "modules" or "ships" are ) if the player has the possibility to send those datas...

This shouldn't affect eddn stability but simply has to implement that 4th schema... that it will be quite identical to "modules"

**Comment by AnthorNet** [comment]
I personally don't see the point of having a schema if the special modules are dependant on power play in station.
It uses bandwidth and CPU, for something that is dependant for informations we do not send.

Again I'm not aware of the exact functioning process, so it must be discussed.

**Comment by koreldan** [comment]
It simply sounds strange to me that those modules are ignored and that special rules was been created to ignore them and in  the other hand the info from Elite OCR are taken as they are, also if a cmdr simply forget to analyze a screenshot or forget to send part of its data or simply he sent wrong datas...

**Comment by jamesremuscat** [comment]
Marginal's comment at https://github.com/Marginal/EDMarketConnector/issues/40#issuecomment-155472176 explains why it doesn't make much sense to broadcast data about prices for these modules.
