### ISSUE TITLE
Outfitting schema doesn't support Class G and H modules

### ISSUE THREAD

**Issue by Marginal** [jamesremuscat/EDDN#38]
[Planetary Vehicle Hangar](http://elite-dangerous.wikia.com/wiki/Planetary_Vehicle_Hangar) comes in ratings G and H.
outfitting/1 schema doesn't allow these.
I get:
`FAIL: [<ValidationError: "{'category': 'internal', 'rating': 'H', 'name': 'Planetary Vehicle Hangar', 'class': '2'} is not valid under any of the given schemas">]`

**Comment by AnthorNet** [comment]
Fixed in https://github.com/jamesremuscat/EDDN/commit/fa0897b985a265e07ceb245623b79f5fbebb6634

**Comment by AnthorNet** [comment]
Was G not supported?

**Comment by Marginal** [comment]
Maybe G was supported - I was writing in a hurry.

**Comment by Marginal** [comment]
Thanks - [working now](https://ross.eddb.io/eddn/log/6440915).
