### ISSUE TITLE
Question is it acceptable to send 'null' instead of sending nothing?

### ISSUE THREAD

**Issue by rcthelp** [jamesremuscat/EDDN#39]
For example:

      {
        "name": "Imperial Slaves",
        "buyPrice": 0,
        "supplyLevel": null,
        "demandLevel": "Low",
        "supply": 0,
        "demand": 105,
        "sellPrice": 15859
      },

**Comment by Marginal** [comment]
Not according to the [current schema](https://github.com/jamesremuscat/EDDN/blob/master/schemas/commodity-v2.0.json#L71).

**Comment by rcthelp** [comment]
Thanks. In fact, in the end I validated the output against the schema in code (VB) using Json.Net from Newtonsoft.
