### ISSUE TITLE
EDDN stats get no updates anymore

### ISSUE THREAD

**Issue by Duke-Jones** [jamesremuscat/EDDN#44]
Hi,

since a few days the states are not updated anymore:

http://eddn.ed-td.space/#software
http://eddn.ed-td.space/#uploaders
http://eddn.ed-td.space/#schemas

**Comment by AnthorNet** [comment]
Restarted the monitor ;)

**Comment by Duke-Jones** [comment]
happen again ?

**Comment by AnthorNet** [comment]
Restarted the monitor, just in case, but there is some number today.
May be because of week and beta

**Comment by Duke-Jones** [comment]
No, the message count of the last hour (to relays ~ 160)  is 
already more than the total count of messages by software today (~70).

**Comment by Duke-Jones** [comment]
dead again ?
