### ISSUE TITLE
Schema needs updating for 2.1 new weapons?

### ISSUE THREAD

**Issue by Athanasius** [jamesremuscat/EDDN#45]
See this issue: https://github.com/Marginal/EDMarketConnector/issues/113

Particularly: https://github.com/Marginal/EDMarketConnector/issues/113#issuecomment-222302406

**Comment by AnthorNet** [comment]
Hi,
I'm aware of that one, but not at home this week end to run all needed tests.

**Comment by Marginal** [comment]
The schema is fine. EDMC needs an [update](https://github.com/Marginal/EDMarketConnector/issues/113#issuecomment-222303034).
